### ISSUE TITLE
Steps are inappropriately skipped even when changed files match the filter

### ISSUE THREAD

**Issue by tylerlaprade** [tony84727/changed-file-filter#47] opened 2024-07-30 14:41 UTC
I made a PR with three commits in it. The final commit only touched a few files, so the changed file filter thought only those files were changed, and my other actions were skipped.

**Comment by tony84727** [comment] 2024-07-31 14:06
Hello, did some of the changes get merged into the target branch first?

Because the action uses `git diff` to compare versions of source branch and target branch.

Say, the pull requests consists of three commits. But the first commit was cherry-picked by others and merged into the same target branch (normally `main` or `master`). When next time the action runs, changes of the first commit will be excluded from the diff and not reported as changed.

**Comment by tylerlaprade** [comment] 2024-07-31 19:15
No, none of the commits were merged. All were still pending, and the changed file filter skipped out lints and tests without us realizing, so we merged the entire PR all at once.

**Comment by tylerlaprade** [comment] 2024-08-01 16:53
Update on this issue:
The "multiple commits" may have been a red herring. I just observed the same behavior on a PR with only one commit.
```yaml
runs:
  using: 'composite'
  steps:
    - uses: tony84727/changed-file-filter@v0.2.3
      id: filter
      with:
        filters: |
          hanaq:
            - '.github/**/*'
            - 'hanaq/**/*'
            - '.ruff.toml'
            - 'pyrightconfig.json'
          paqarina:
            - '.github/**/*'
            - 'paqarina/**/*'
```
![image](https://github.com/user-attachments/assets/5ba5fa59-6160-4ce6-966a-5036294f07d7)

I verified in the GitHub Action logs that these `paqarina/` files were in the (long) list of files that were changed. Could they have been excluded because they were at the very end, or what happened here?

**Comment by tony84727** [comment] 2024-08-03 06:09
I created a [repository](https://github.com/tony84727/changed-file-filter-47) using the rules you provided and added some dummy files through PRs. But I didn't find any unexpected behaviors.

From the snippet you provided, the filter seems to belong to a composite action. I added a [composite action](https://github.com/tony84727/changed-file-filter-47/blob/c1a6e462c8d7ba2bad882de82b0277022dc006ab/.github/actions/checks/action.yaml#L3-L17) when testing.

Both [PR](https://github.com/tony84727/changed-file-filter-47/actions/runs/10225717724/job/28295074229#step:3:33) and [merge](https://github.com/tony84727/changed-file-filter-47/actions/runs/10225734122/job/28295116026#step:3:33) changes were detected.

> I verified in the GitHub Action logs that these paqarina/ files were in the (long) list of files that were changed. Could they have been excluded because they were at the very end, or what happened here

Can you give me a ballpark figure of how many files were changed? Very long change list could potentially be an edge case because the action call `git` and parse its output. If output gets truncated because of some unknown limit, it could be the culprit

**Comment by tony84727** [comment] 2024-08-10 09:33
>  I noticed the same problem happened again on another large PR with 197 files changed, so I'm beginning to think that's the culprit.

Yes, I can confirm that from my test reuslts.
Found that the action didn't receive the complete stdout when calling git but merely the first output buffer.

I've opened #50 to fix this. Thanks!

**Closed** 2024-08-10 09:34 UTC

**Comment by tony84727** [comment] 2024-08-10 09:43
@tylerlaprade  `v0.2.4` released. If that didn't resolve your issue please reopen this one or create a new issue. Thank you.

**Comment by tylerlaprade** [comment] 2024-08-12 16:31
Thank you so much! Looking forward to trying this out.
